title: Shingo Yashima
logo: 
description: Researcher @ [Denso IT Laboratory, inc.](https://www.d-itlab.co.jp/)
show_downloads: False
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
github:
  owner_url: 
  another_url: another value

